package es.fdeazagra.tpvfastfood.principal;

import es.fdeazagra.tpvfastfood.acciones.AccionesCliente;
import es.fdeazagra.tpvfastfood.acciones.AccionesTicket;
import es.fdeazagra.tpvfastfood.gestionbd.Producto;
import es.fdeazagra.tpvfastfood.gestionbd.ServiceCliente;
import es.fdeazagra.tpvfastfood.gestionbd.ServiceTicket;
import es.fdeazagra.tpvfastfood.vistas.PanelBebidas;
import es.fdeazagra.tpvfastfood.vistas.PanelClientes;
import es.fdeazagra.tpvfastfood.vistas.PanelExtras;
import es.fdeazagra.tpvfastfood.vistas.PanelHamburguesas;
import es.fdeazagra.tpvfastfood.vistas.PanelMenus;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 * Clase con la ventana principal de la aplicación.
 *
 * @author Fernando Martínez de Azagra.
 */
public class TPVFrame extends javax.swing.JFrame {

   
    private PanelClientes panel;
    /**
     * Constructor de la interfaz gráfica de la aplicación.
     */
    public TPVFrame() {
        initComponents();
        
        PanelHamburguesas panelHamburguesas = new PanelHamburguesas(this);
        pnlMedio.add(panelHamburguesas, java.awt.BorderLayout.CENTER);
        pack();
        
                
        Producto start = new Producto();
        start.inicializarLista();
        
        AccionesTicket accion = new AccionesTicket(this);
        lblFecha.setText(accion.fechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEtiquetasNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnFichaCliente = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        pnlCategorias = new javax.swing.JPanel();
        btnMenus = new javax.swing.JButton();
        btnHamburguesas = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnExtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlMedio = new javax.swing.JPanel();
        pnlPantalla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPantalla = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnVentasFecha = new javax.swing.JButton();
        btnVentasCliente = new javax.swing.JButton();
        btnListaClientes = new javax.swing.JButton();
        panelBotonesSur = new javax.swing.JPanel();
        btnCorregir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnClienteHabitual = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProductos = new javax.swing.JMenu();
        menuProductosBebidas = new javax.swing.JMenuItem();
        menuProductosMenus = new javax.swing.JMenuItem();
        menuProductosHamburguesas = new javax.swing.JMenuItem();
        menuProductosExtras = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuClientesFicha = new javax.swing.JMenuItem();
        menuClientesLista = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        menuVentasCliente = new javax.swing.JMenuItem();
        menuVentasFecha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setMaximumSize(new java.awt.Dimension(1280, 740));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(1280, 740));
        setResizable(false);

        panelEtiquetasNorte.setBackground(new java.awt.Color(185, 224, 185));
        panelEtiquetasNorte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEtiquetasNorte.setMinimumSize(new java.awt.Dimension(900, 35));
        panelEtiquetasNorte.setPreferredSize(new java.awt.Dimension(1200, 50));
        panelEtiquetasNorte.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setText("Id. Cliente:");
        panelEtiquetasNorte.add(jLabel1);

        lblIdCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblIdCliente.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIdCliente.setMaximumSize(new java.awt.Dimension(100, 20));
        lblIdCliente.setMinimumSize(new java.awt.Dimension(40, 20));
        lblIdCliente.setOpaque(true);
        lblIdCliente.setPreferredSize(new java.awt.Dimension(60, 20));
        panelEtiquetasNorte.add(lblIdCliente);

        jLabel5.setText("Nombre:");
        panelEtiquetasNorte.add(jLabel5);

        lblNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreCliente.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombreCliente.setMaximumSize(new java.awt.Dimension(300, 20));
        lblNombreCliente.setMinimumSize(new java.awt.Dimension(200, 20));
        lblNombreCliente.setOpaque(true);
        lblNombreCliente.setPreferredSize(new java.awt.Dimension(200, 20));
        panelEtiquetasNorte.add(lblNombreCliente);

        jSeparator4.setMinimumSize(new java.awt.Dimension(80, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 0));
        panelEtiquetasNorte.add(jSeparator4);

        btnFichaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/clientes.png"))); // NOI18N
        btnFichaCliente.setText("Ficha Cliente");
        btnFichaCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnFichaCliente.setMaximumSize(new java.awt.Dimension(200, 40));
        btnFichaCliente.setMinimumSize(new java.awt.Dimension(120, 30));
        btnFichaCliente.setPreferredSize(new java.awt.Dimension(120, 30));
        btnFichaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaClienteActionPerformed(evt);
            }
        });
        panelEtiquetasNorte.add(btnFichaCliente);

        jSeparator5.setMinimumSize(new java.awt.Dimension(50, 0));
        jSeparator5.setPreferredSize(new java.awt.Dimension(430, 0));
        panelEtiquetasNorte.add(jSeparator5);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setMaximumSize(new java.awt.Dimension(100, 20));
        lblFecha.setMinimumSize(new java.awt.Dimension(80, 20));
        lblFecha.setPreferredSize(new java.awt.Dimension(80, 20));
        panelEtiquetasNorte.add(lblFecha);

        getContentPane().add(panelEtiquetasNorte, java.awt.BorderLayout.NORTH);

        panelPrincipal.setMinimumSize(new java.awt.Dimension(900, 450));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 600));
        panelPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        pnlCategorias.setBackground(new java.awt.Color(185, 224, 185));
        pnlCategorias.setMinimumSize(new java.awt.Dimension(180, 327));
        pnlCategorias.setPreferredSize(new java.awt.Dimension(180, 327));
        pnlCategorias.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 2));

        btnMenus.setBackground(new java.awt.Color(0, 153, 0));
        btnMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/menus.png"))); // NOI18N
        btnMenus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Menús", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Schoolbook", 1, 18))); // NOI18N
        btnMenus.setMaximumSize(new java.awt.Dimension(200, 165));
        btnMenus.setMinimumSize(new java.awt.Dimension(140, 145));
        btnMenus.setPreferredSize(new java.awt.Dimension(185, 145));
        btnMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenusActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnMenus);

        btnHamburguesas.setBackground(new java.awt.Color(0, 153, 0));
        btnHamburguesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/hamburgesa.png"))); // NOI18N
        btnHamburguesas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Burgers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Schoolbook", 1, 18))); // NOI18N
        btnHamburguesas.setMaximumSize(new java.awt.Dimension(200, 165));
        btnHamburguesas.setMinimumSize(new java.awt.Dimension(140, 145));
        btnHamburguesas.setPreferredSize(new java.awt.Dimension(185, 145));
        btnHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnHamburguesas);

        btnBebidas.setBackground(new java.awt.Color(0, 153, 0));
        btnBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/bebidas.png"))); // NOI18N
        btnBebidas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Bebidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Schoolbook", 1, 18))); // NOI18N
        btnBebidas.setMaximumSize(new java.awt.Dimension(200, 145));
        btnBebidas.setMinimumSize(new java.awt.Dimension(140, 165));
        btnBebidas.setPreferredSize(new java.awt.Dimension(185, 145));
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnBebidas);

        btnExtras.setBackground(new java.awt.Color(0, 153, 0));
        btnExtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/extras.png"))); // NOI18N
        btnExtras.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Extras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Schoolbook", 1, 18))); // NOI18N
        btnExtras.setMaximumSize(new java.awt.Dimension(200, 145));
        btnExtras.setPreferredSize(new java.awt.Dimension(185, 145));
        btnExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtrasActionPerformed(evt);
            }
        });
        pnlCategorias.add(btnExtras);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 255));

        tblTabla.setAutoCreateRowSorter(true);
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblTabla.setEnabled(false);
        tblTabla.setFocusable(false);
        tblTabla.setMaximumSize(new java.awt.Dimension(600, 600));
        tblTabla.setMinimumSize(new java.awt.Dimension(45, 30));
        tblTabla.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(tblTabla);
        if (tblTabla.getColumnModel().getColumnCount() > 0) {
            tblTabla.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblTabla.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblTabla.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        pnlCategorias.add(jScrollPane1);

        jSeparator2.setPreferredSize(new java.awt.Dimension(400, 5));
        pnlCategorias.add(jSeparator2);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel6.setText("Total:");
        pnlCategorias.add(jLabel6);

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.0 €");
        lblTotal.setAlignmentX(2.0F);
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal.setOpaque(true);
        lblTotal.setPreferredSize(new java.awt.Dimension(250, 25));
        pnlCategorias.add(lblTotal);

        panelPrincipal.add(pnlCategorias);

        pnlMedio.setBackground(new java.awt.Color(102, 255, 102));
        pnlMedio.setLayout(new java.awt.BorderLayout());
        panelPrincipal.add(pnlMedio);

        pnlPantalla.setBackground(new java.awt.Color(185, 224, 185));
        pnlPantalla.setLayout(new java.awt.BorderLayout());

        tblPantalla.setBackground(new java.awt.Color(255, 255, 204));
        tblPantalla.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblPantalla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "HORA", "ID CLIENTE", "ID TICKET", "TOTAL"
            }
        ));
        tblPantalla.setFocusable(false);
        tblPantalla.setMaximumSize(new java.awt.Dimension(600, 30000));
        tblPantalla.setPreferredSize(new java.awt.Dimension(450, 600));
        jScrollPane2.setViewportView(tblPantalla);
        if (tblPantalla.getColumnModel().getColumnCount() > 0) {
            tblPantalla.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPantalla.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblPantalla.getColumnModel().getColumn(2).setPreferredWidth(95);
            tblPantalla.getColumnModel().getColumn(3).setPreferredWidth(95);
            tblPantalla.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        pnlPantalla.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(204, 204, 0));
        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotones.setMinimumSize(new java.awt.Dimension(300, 70));
        pnlBotones.setPreferredSize(new java.awt.Dimension(400, 42));

        btnVentasFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/fecha.png"))); // NOI18N
        btnVentasFecha.setText("Ventas Fecha");
        btnVentasFecha.setMaximumSize(new java.awt.Dimension(200, 40));
        btnVentasFecha.setMinimumSize(new java.awt.Dimension(100, 20));
        btnVentasFecha.setPreferredSize(new java.awt.Dimension(130, 30));
        btnVentasFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasFechaActionPerformed(evt);
            }
        });
        pnlBotones.add(btnVentasFecha);

        btnVentasCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/venta_cliente.png"))); // NOI18N
        btnVentasCliente.setText("Ventas Cliente");
        btnVentasCliente.setMaximumSize(new java.awt.Dimension(100, 40));
        btnVentasCliente.setMinimumSize(new java.awt.Dimension(80, 20));
        btnVentasCliente.setPreferredSize(new java.awt.Dimension(130, 30));
        btnVentasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasClienteActionPerformed(evt);
            }
        });
        pnlBotones.add(btnVentasCliente);

        btnListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/datos.png"))); // NOI18N
        btnListaClientes.setText("Clientes");
        btnListaClientes.setMaximumSize(new java.awt.Dimension(200, 40));
        btnListaClientes.setMinimumSize(new java.awt.Dimension(80, 20));
        btnListaClientes.setPreferredSize(new java.awt.Dimension(100, 30));
        btnListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaClientesActionPerformed(evt);
            }
        });
        pnlBotones.add(btnListaClientes);

        pnlPantalla.add(pnlBotones, java.awt.BorderLayout.SOUTH);

        panelPrincipal.add(pnlPantalla);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        panelBotonesSur.setBackground(new java.awt.Color(185, 224, 185));
        panelBotonesSur.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBotonesSur.setMinimumSize(new java.awt.Dimension(900, 40));
        panelBotonesSur.setPreferredSize(new java.awt.Dimension(1200, 40));
        panelBotonesSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 3));

        btnCorregir.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnCorregir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/corregir.png"))); // NOI18N
        btnCorregir.setText("Corregir");
        btnCorregir.setMinimumSize(new java.awt.Dimension(80, 20));
        btnCorregir.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorregirActionPerformed(evt);
            }
        });
        panelBotonesSur.add(btnCorregir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 40));
        btnCancelar.setMinimumSize(new java.awt.Dimension(80, 20));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBotonesSur.add(btnCancelar);

        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/check.png"))); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.setMaximumSize(new java.awt.Dimension(100, 40));
        btnCobrar.setMinimumSize(new java.awt.Dimension(80, 20));
        btnCobrar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        panelBotonesSur.add(btnCobrar);

        jSeparator3.setPreferredSize(new java.awt.Dimension(150, 0));
        panelBotonesSur.add(jSeparator3);

        btnClienteHabitual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/descuento.png"))); // NOI18N
        btnClienteHabitual.setText("Cobrar Cliente Habitual");
        btnClienteHabitual.setToolTipText("contraseña: admin");
        btnClienteHabitual.setMaximumSize(new java.awt.Dimension(200, 40));
        btnClienteHabitual.setMinimumSize(new java.awt.Dimension(100, 20));
        btnClienteHabitual.setPreferredSize(new java.awt.Dimension(200, 30));
        btnClienteHabitual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteHabitualActionPerformed(evt);
            }
        });
        panelBotonesSur.add(btnClienteHabitual);

        jSeparator1.setPreferredSize(new java.awt.Dimension(320, 0));
        panelBotonesSur.add(jSeparator1);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/fdeazagra/tpvfastfood/principal/logo.png"))); // NOI18N
        panelBotonesSur.add(jLabel4);

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("The Burger Corner");
        panelBotonesSur.add(jLabel2);

        getContentPane().add(panelBotonesSur, java.awt.BorderLayout.SOUTH);

        menuProductos.setText("Productos");

        menuProductosBebidas.setText("Bebidas");
        menuProductosBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosBebidasActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosBebidas);

        menuProductosMenus.setText("Menús");
        menuProductosMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosMenusActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosMenus);

        menuProductosHamburguesas.setText("Hamburguesas");
        menuProductosHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosHamburguesasActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosHamburguesas);

        menuProductosExtras.setText("Extras");
        menuProductosExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosExtrasActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosExtras);

        jMenuBar1.add(menuProductos);

        menuClientes.setText("Clientes");

        menuClientesFicha.setText("Ficha cliente");
        menuClientesFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesFichaActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesFicha);

        menuClientesLista.setText("Lista clientes");
        menuClientesLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesListaActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesLista);

        jMenuBar1.add(menuClientes);

        menuVentas.setText("Ventas");

        menuVentasCliente.setText("Ventas Cliente");
        menuVentasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasClienteActionPerformed(evt);
            }
        });
        menuVentas.add(menuVentasCliente);

        menuVentasFecha.setText("Ventas Fecha");
        menuVentasFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasFechaActionPerformed(evt);
            }
        });
        menuVentas.add(menuVentasFecha);

        jMenuBar1.add(menuVentas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que abre desde el menú el el listado de los tickets de una fecha.
     * 
     * @param evt ActionEvernt
     */
    private void menuVentasFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasFechaActionPerformed
        
        ServiceTicket service = new ServiceTicket(this);
        
        try {
            service.ticketsFecha();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuVentasFechaActionPerformed

    /**
     * Método que acciona el botón para abrir el panel con los productos de
     * la categoría Menús.
     * 
     * @param evt ActionEvernt
     */
    private void btnMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenusActionPerformed
        
        PanelMenus panelMenus = new PanelMenus(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelMenus, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_btnMenusActionPerformed

    /**
     * Método que abre desde el menú el panel con los productos de
     * la categoría Menús.
     * 
     * @param evt ActionEvernt
     */
    private void menuProductosMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosMenusActionPerformed
        
        PanelMenus panelMenus = new PanelMenus(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelMenus, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_menuProductosMenusActionPerformed

    /**
     * Método que acciona el botón para abrir el panel con los productos de
     * la categoría Hamburguesas.
     * 
     * @param evt ActionEvernt
     */
    private void btnHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesasActionPerformed
        
        PanelHamburguesas panelHamburguesas = new PanelHamburguesas(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelHamburguesas, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_btnHamburguesasActionPerformed

    /**
     * Método que abre desde el menú el panel con los productos de
     * la categoría Hamburguesas.
     * 
     * @param evt ActionEvernt
     */
    private void menuProductosHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosHamburguesasActionPerformed
       
        PanelHamburguesas panelHamburguesas = new PanelHamburguesas(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelHamburguesas, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_menuProductosHamburguesasActionPerformed

    /**
     * Método que abre desde el menú el panel con los productos de
     * la categoría Extras.
     * 
     * @param evt ActionEvernt
     */
    private void menuProductosExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosExtrasActionPerformed
        
        PanelExtras panelExtras = new PanelExtras(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelExtras, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_menuProductosExtrasActionPerformed

    /**
     * Método que acciona el botón para abrir el panel con los productos de
     * la categoría Extras.
     * 
     * @param evt ActionEvernt
     */
    private void btnExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtrasActionPerformed
        
        PanelExtras panelExtras = new PanelExtras(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelExtras, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_btnExtrasActionPerformed

    /**
     * Método que acciona el botón para abrir el panel con los productos de
     * la categoría Bebidas.
     * 
     * @param evt ActionEvernt
     */
    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        
        PanelBebidas panelBebidas = new PanelBebidas(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelBebidas, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_btnBebidasActionPerformed

  
    /**
     * Método que abre desde el menú el panel con los productos de
     * la categoría bebidas.
     * 
     * @param evt ActionEvernt
     */
    private void menuProductosBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosBebidasActionPerformed
        
        PanelBebidas panelBebidas = new PanelBebidas(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelBebidas, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_menuProductosBebidasActionPerformed

    /**
     * Método que acciona el botón para abrir el panel ficha de clientes.
     * 
     * @param evt ActionEvernt
     */
    private void btnFichaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaClienteActionPerformed
       
        PanelClientes panelClientes = new PanelClientes(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelClientes, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_btnFichaClienteActionPerformed

    /**
     * Método que abre desde el menú el panel ficha de clientes.
     * 
     * @param evt ActionEvernt
     */
    private void menuClientesFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesFichaActionPerformed
       
        PanelClientes panelClientes = new PanelClientes(this);
        pnlMedio.removeAll();
        pnlMedio.add(panelClientes, java.awt.BorderLayout.CENTER);
        pnlMedio.repaint();
        pack();
    }//GEN-LAST:event_menuClientesFichaActionPerformed

    /**
     * Método que abre desde el menú el listado de los tickets de un cliente.
     * 
     * @param evt ActionEvernt
     */
    private void menuVentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasClienteActionPerformed
        
        ServiceTicket service = new ServiceTicket(this);
        
        try {
            service.ticketsCliente();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuVentasClienteActionPerformed

    /**
     * Método que abre desde el menú la lista de clientes registrados.
     * 
     * @param evt ActionEvernt
     */
    private void menuClientesListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesListaActionPerformed
        
        ServiceCliente service = new ServiceCliente(panel, this);
        
        try {
            service.listaClientes();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuClientesListaActionPerformed

    /**
     * Método que acciona el botón para cobrar el pedido actual 
     * en pantalla e imprimir el ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        
        AccionesTicket accion = new AccionesTicket(this);
        ServiceTicket service = new ServiceTicket(this);
        boolean control = accion.compruebaTablaVacia();
        
        if (control == true){
            
            JOptionPane.showMessageDialog(null, accion.creaTicket().toString());

            try {
                
                service.saveTicket(accion.creaTicket());
                
            } catch (SQLException ex) {

                Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE,null,ex);
            }

            accion.vaciaLista();
            accion.vaciaDatos();
            
        } else{
            
            JOptionPane.showMessageDialog(null, "¡Pantalla vacía!");
        }
        
    }//GEN-LAST:event_btnCobrarActionPerformed

    /**
     * Método que acciona el botón para cancelar el pedido actual en pantalla.
     * 
     * @param evt ActionEvernt
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        AccionesTicket accion = new AccionesTicket(this);
        accion.vaciaLista();
        accion.vaciaDatos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que acciona el botón para retroceder el último movimiento 
     * del pedido actual en pantalla.
     * 
     * @param evt ActionEvernt
     */
    private void btnCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorregirActionPerformed
        
        AccionesTicket accion = new AccionesTicket(this);
        accion.retrocedeVenta();
    }//GEN-LAST:event_btnCorregirActionPerformed

    /**
     * Método que acciona el botón de descuento a cliente habitual.
     * Solicita contraseña para continuar.
     * 
     * @param evt ActionEvernt
     */
    private void btnClienteHabitualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteHabitualActionPerformed
        
        AccionesCliente accion = new AccionesCliente(this, panel);
        AccionesTicket accionT = new AccionesTicket(this);
        boolean control = accionT.compruebaTablaVacia();
        
        if (control == true){
            
            accion.solicitaPassword();
            
        } else{
            
            JOptionPane.showMessageDialog(null, "¡Pantalla vacía!");
        }
    }//GEN-LAST:event_btnClienteHabitualActionPerformed

    /**
     * Método que acciona el botón para listar los clientes registrados.
     * 
     * @param evt ActionEvernt
     */
    private void btnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaClientesActionPerformed
        
        ServiceCliente service = new ServiceCliente(panel, this);
        
        try {
            service.listaClientes();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListaClientesActionPerformed

    /**
     * Método que acciona el botón para listar las ventas de un cliente.
     * 
     * @param evt ActionEvernt
     */
    private void btnVentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasClienteActionPerformed
        
        ServiceTicket service = new ServiceTicket(this);
        
        try {
            service.ticketsCliente();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVentasClienteActionPerformed

    /**
     * Método que acciona el botón para listar las ventas de una fecha concreta.
     * 
     * @param evt ActionEvernt
     */
    private void btnVentasFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasFechaActionPerformed
        
        ServiceTicket service = new ServiceTicket(this);
        
        try {
            service.ticketsFecha();
        } catch (SQLException ex) {
            Logger.getLogger(TPVFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVentasFechaActionPerformed


    /**
     * Getter del JTable de la pantalla de tickets.
     *
     * @return JTable tblTabla.
     */
    public JTable getTblTabla() {
        return tblTabla;
    }

    /**
     * Getter del JTable de la pantalla para la base de datos.
     *
     * @return JTable tblPantalla.
     */
    public JTable getTblPantalla() {
        return tblPantalla;
    }
    
    

    /**
     * Getter del JLabel con el total de la pantalla de tickets.
     *
     * @return JLabel lblTotal.
     */
    public JLabel getLblTotal() {
        return lblTotal;
    }

    /**
     * Getter del JLabel con el id del cliente de la ventana principal.
     *
     * @return JLabel lblIdCliente.
     */
    public JLabel getLblIdCliente() {
        return lblIdCliente;
    }

    /**
     * Getter del JLabel con el nombre del cliente de la ventana principal.
     *
     * @return JLabel lblNombreCliente.
     */
    public JLabel getLblNombreCliente() {
        return lblNombreCliente;
    }

    
    
    

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPVFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClienteHabitual;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnCorregir;
    private javax.swing.JButton btnExtras;
    private javax.swing.JButton btnFichaCliente;
    private javax.swing.JButton btnHamburguesas;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnMenus;
    private javax.swing.JButton btnVentasCliente;
    private javax.swing.JButton btnVentasFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesFicha;
    private javax.swing.JMenuItem menuClientesLista;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenuItem menuProductosBebidas;
    private javax.swing.JMenuItem menuProductosExtras;
    private javax.swing.JMenuItem menuProductosHamburguesas;
    private javax.swing.JMenuItem menuProductosMenus;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenuItem menuVentasCliente;
    private javax.swing.JMenuItem menuVentasFecha;
    private javax.swing.JPanel panelBotonesSur;
    private javax.swing.JPanel panelEtiquetasNorte;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JTable tblPantalla;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
}
