package es.fdeazagra.tpvfastfood.vistas;

import es.fdeazagra.tpvfastfood.acciones.AccionesTicket;
import es.fdeazagra.tpvfastfood.gestionbd.Producto;
import es.fdeazagra.tpvfastfood.principal.TPVFrame;

/**
 * Clase con el panel con los productos de la categoría bebidas.
 *
 * @author Fernando Martínez de Azagra
 */
public class PanelBebidas extends javax.swing.JPanel {

    private final TPVFrame frame;
    
    /**
     * Constructor del panel con los productos de la categoría bebidas.
     * 
     * @param frame ventana principal de la aplicación.
     */
    public PanelBebidas(TPVFrame frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProducto19 = new javax.swing.JButton();
        btnProducto20 = new javax.swing.JButton();
        btnProducto21 = new javax.swing.JButton();
        btnProducto22 = new javax.swing.JButton();
        btnProducto23 = new javax.swing.JButton();
        btnProducto24 = new javax.swing.JButton();
        btnProducto25 = new javax.swing.JButton();
        btnProducto26 = new javax.swing.JButton();
        btnProducto27 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new java.awt.GridLayout(3, 2, 3, 3));

        btnProducto19.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto19.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto19.setText("Vino");
        btnProducto19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto19ActionPerformed(evt);
            }
        });
        add(btnProducto19);

        btnProducto20.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto20.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto20.setText("Caña");
        btnProducto20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto20ActionPerformed(evt);
            }
        });
        add(btnProducto20);

        btnProducto21.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto21.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        btnProducto21.setText("Caña Sin");
        btnProducto21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto21ActionPerformed(evt);
            }
        });
        add(btnProducto21);

        btnProducto22.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto22.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto22.setText("Refresco");
        btnProducto22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto22ActionPerformed(evt);
            }
        });
        add(btnProducto22);

        btnProducto23.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto23.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto23.setText("Zumo");
        btnProducto23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto23ActionPerformed(evt);
            }
        });
        add(btnProducto23);

        btnProducto24.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto24.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto24.setText("Batido");
        btnProducto24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto24ActionPerformed(evt);
            }
        });
        add(btnProducto24);

        btnProducto25.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto25.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto25.setText("Café");
        btnProducto25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto25ActionPerformed(evt);
            }
        });
        add(btnProducto25);

        btnProducto26.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto26.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto26.setText("Infusión");
        btnProducto26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto26ActionPerformed(evt);
            }
        });
        add(btnProducto26);

        btnProducto27.setBackground(new java.awt.Color(216, 238, 34));
        btnProducto27.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnProducto27.setText("Agua");
        btnProducto27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto27ActionPerformed(evt);
            }
        });
        add(btnProducto27);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que acciona el botón para añadir el producto 19 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto19ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(19));
        accion.productoATicket(Producto.listaDeProductos.get(19));
    }//GEN-LAST:event_btnProducto19ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 20 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto20ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(20));
        accion.productoATicket(Producto.listaDeProductos.get(20));
    }//GEN-LAST:event_btnProducto20ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 21 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto21ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(21));
        accion.productoATicket(Producto.listaDeProductos.get(21));
    }//GEN-LAST:event_btnProducto21ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 22 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto22ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(22));
        accion.productoATicket(Producto.listaDeProductos.get(22));
    }//GEN-LAST:event_btnProducto22ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 23 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto23ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(23));
        accion.productoATicket(Producto.listaDeProductos.get(23));
    }//GEN-LAST:event_btnProducto23ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 24 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto24ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(24));
        accion.productoATicket(Producto.listaDeProductos.get(24));
    }//GEN-LAST:event_btnProducto24ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 25 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto25ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(25));
        accion.productoATicket(Producto.listaDeProductos.get(25));
    }//GEN-LAST:event_btnProducto25ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 26 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto26ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(26));
        accion.productoATicket(Producto.listaDeProductos.get(26));
    }//GEN-LAST:event_btnProducto26ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 27 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto27ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(27));
        accion.productoATicket(Producto.listaDeProductos.get(27));
    }//GEN-LAST:event_btnProducto27ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProducto19;
    private javax.swing.JButton btnProducto20;
    private javax.swing.JButton btnProducto21;
    private javax.swing.JButton btnProducto22;
    private javax.swing.JButton btnProducto23;
    private javax.swing.JButton btnProducto24;
    private javax.swing.JButton btnProducto25;
    private javax.swing.JButton btnProducto26;
    private javax.swing.JButton btnProducto27;
    // End of variables declaration//GEN-END:variables
}
