package es.fdeazagra.tpvfastfood.vistas;

import es.fdeazagra.tpvfastfood.acciones.AccionesTicket;
import es.fdeazagra.tpvfastfood.gestionbd.Producto;
import es.fdeazagra.tpvfastfood.principal.TPVFrame;

/**
 * Clase con el panel con los productos de la categoría menús.
 *
 * @author Fernando Martínez de Azagra
 */
public class PanelMenus extends javax.swing.JPanel {

    private final TPVFrame frame;
    
    /**
     * Constructor del panel con los productos de la categoría menús.
     * 
     * @param frame ventana principal de la aplicación.
     */
    public PanelMenus(TPVFrame frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProducto1 = new javax.swing.JButton();
        btnProducto2 = new javax.swing.JButton();
        btnProducto3 = new javax.swing.JButton();
        btnProducto4 = new javax.swing.JButton();
        btnProducto5 = new javax.swing.JButton();
        btnProducto6 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new java.awt.GridLayout(3, 2, 3, 3));

        btnProducto1.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto1.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto1.setText("Menú nº1");
        btnProducto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto1ActionPerformed(evt);
            }
        });
        add(btnProducto1);

        btnProducto2.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto2.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto2.setText("Menú nº2");
        btnProducto2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto2ActionPerformed(evt);
            }
        });
        add(btnProducto2);

        btnProducto3.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto3.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto3.setText("Menú nº3");
        btnProducto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto3ActionPerformed(evt);
            }
        });
        add(btnProducto3);

        btnProducto4.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto4.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto4.setText("Menú nº4");
        btnProducto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto4ActionPerformed(evt);
            }
        });
        add(btnProducto4);

        btnProducto5.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto5.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto5.setText("Menú nº5");
        btnProducto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto5ActionPerformed(evt);
            }
        });
        add(btnProducto5);

        btnProducto6.setBackground(new java.awt.Color(153, 153, 0));
        btnProducto6.setFont(new java.awt.Font("Century Schoolbook", 1, 21)); // NOI18N
        btnProducto6.setText("Menú nº6");
        btnProducto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto6ActionPerformed(evt);
            }
        });
        add(btnProducto6);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que acciona el botón para añadir el producto 1 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto1ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(1));
        accion.productoATicket(Producto.listaDeProductos.get(1));
    }//GEN-LAST:event_btnProducto1ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 2 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto2ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(2));
        accion.productoATicket(Producto.listaDeProductos.get(2));
    }//GEN-LAST:event_btnProducto2ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 3 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto3ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(3));
        accion.productoATicket(Producto.listaDeProductos.get(3));
    }//GEN-LAST:event_btnProducto3ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 4 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto4ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(4));
        accion.productoATicket(Producto.listaDeProductos.get(4));
    }//GEN-LAST:event_btnProducto4ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 5 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto5ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(5));
        accion.productoATicket(Producto.listaDeProductos.get(5));
    }//GEN-LAST:event_btnProducto5ActionPerformed

    /**
     * Método que acciona el botón para añadir el producto 6 al ticket.
     * 
     * @param evt ActionEvernt
     */
    private void btnProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto6ActionPerformed
        
        AccionesTicket accion = new AccionesTicket(frame);
        accion.productoAPantalla(Producto.listaDeProductos.get(6));
        accion.productoATicket(Producto.listaDeProductos.get(6));
    }//GEN-LAST:event_btnProducto6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProducto1;
    private javax.swing.JButton btnProducto2;
    private javax.swing.JButton btnProducto3;
    private javax.swing.JButton btnProducto4;
    private javax.swing.JButton btnProducto5;
    private javax.swing.JButton btnProducto6;
    // End of variables declaration//GEN-END:variables
}
